-- ============================================================
-- Final schema for Stripe-integrated MyPage
-- Purpose:
--   - Persist linkage to Stripe customer and cached plan (user_stripe)
--   - Store newsletter/notification recipients (recipient_emails)
-- Notes:
--   - Supabase Auth is NOT used for this linkage; email may repeat.
--   - user_stripe has 1:N relation to recipient_emails via user_stripe_id.
--   - Writes are performed by server (service role) via webhooks/APIs
--   - Clients read-only; add RLS separately if needed.
-- ============================================================

-- ========================
-- Table: public.user_stripe
-- ========================
create table if not exists public.user_stripe (
  id bigint generated by default as identity primary key,
  email text not null,
  stripe_customer_id text,
  stripe_subscription_id text,
  current_plan text,         -- 'lite' | 'business' | null (cached)
  updated_at timestamptz not null default now()
);

-- Indexes (subscription_id unique; search helpers)
create index if not exists idx_user_stripe_email on public.user_stripe (email);
create index if not exists idx_user_stripe_customer on public.user_stripe (stripe_customer_id);
create index if not exists idx_user_stripe_customer_subscription on public.user_stripe (stripe_customer_id, stripe_subscription_id);
create unique index if not exists uq_user_stripe_subscription_id on public.user_stripe (stripe_subscription_id) where stripe_subscription_id is not null;
create unique index if not exists uq_user_stripe_customer_id on public.user_stripe (stripe_customer_id) where stripe_customer_id is not null;

-- ===============================
-- Table: public.recipient_emails
-- ===============================
create table if not exists public.recipient_emails (
  id bigserial primary key,
  user_stripe_id bigint references public.user_stripe(id) on delete cascade,
  plan text,                      -- 'lite' | 'business' | null (snapshot)
  email text not null,
  created_via text,               -- 'initial' | 'addon' | null
  pending_removal boolean not null default false,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_recipient_emails_user_stripe on public.recipient_emails (user_stripe_id);
create index if not exists idx_recipient_emails_email on public.recipient_emails (email);

-- Global uniqueness of recipient emails
do $$ begin
  alter table public.recipient_emails
    add constraint recipient_unique_email unique (email);
exception when duplicate_object then null; end $$;

-- Notes:
-- - Writes via service role only; add RLS policies if exposing to clients directly.
