-- user_stripe: Stripe鬘ｧ螳｢繝ｻ繧ｵ繝悶せ繧ｯ繝ｪ繝励す繝ｧ繝ｳ縺ｨ繝｡繝ｼ繝ｫ縺ｮ邏蝉ｻ倥￠・・upabase Auth縺ｯ荳堺ｽｿ逕ｨ・・
create table if not exists public.user_stripe (
  id bigint generated by default as identity primary key,
  email text not null,
  stripe_customer_id text,
  stripe_subscription_id text,
  current_plan text,         -- 'lite' | 'business' | null・医く繝｣繝・す繝･・・
  updated_at timestamptz not null default now()
);

-- 蜿ら・逕ｨ繧､繝ｳ繝・ャ繧ｯ繧ｹ繝ｻ荳諢丞宛邏・ｼ・ubscription_id 縺ｯ繧ｰ繝ｭ繝ｼ繝舌Ν荳諢上…ustomer+subscription 縺ｧ繧よ､懃ｴ｢・・
create index if not exists idx_user_stripe_email on public.user_stripe (email);
create index if not exists idx_user_stripe_customer on public.user_stripe (stripe_customer_id);
create index if not exists idx_user_stripe_customer_subscription on public.user_stripe (stripe_customer_id, stripe_subscription_id);
create unique index if not exists uq_user_stripe_subscription_id on public.user_stripe (stripe_subscription_id) where stripe_subscription_id is not null;

-- 霑ｽ蜉驟堺ｿ｡蜈医Γ繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ縺ｮ菫晏ｭ倥ユ繝ｼ繝悶Ν・・ser_stripe 縺ｨ 1:N・・
create table if not exists public.recipient_emails (
  id bigserial primary key,
  user_stripe_id bigint references public.user_stripe(id) on delete cascade,
  plan text,                      -- 'lite' | 'business' | null・井ｿ晏ｭ俶凾轤ｹ縺ｮ繝励Λ繝ｳ・・
  email text not null,
  created_via text,               -- 'initial' | 'addon' | null
  pending_removal boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_recipient_emails_user_stripe on public.recipient_emails (user_stripe_id);
create index if not exists idx_recipient_emails_email on public.recipient_emails (email);

-- 繝｡繝ｼ繝ｫ繧｢繝峨Ξ繧ｹ縺ｯ蜈ｨ菴薙〒繝ｦ繝九・繧ｯ
do $$ begin
  alter table public.recipient_emails
    add constraint recipient_unique_email unique (email);
exception when duplicate_object then null; end $$;
