-- user_stripe: Stripe顧客・サブスクリプションとメールの紐付け（Supabase Authは不使用）
create table if not exists public.user_stripe (
  id bigint generated by default as identity primary key,
  email text not null,
  stripe_customer_id text,
  stripe_subscription_id text,
  current_plan text,         -- 'lite' | 'business' | null（キャッシュ）
  updated_at timestamptz not null default now()
);

-- 参照用インデックス・一意制約（subscription_id はグローバル一意、customer+subscription でも検索）
create index if not exists idx_user_stripe_email on public.user_stripe (email);
create index if not exists idx_user_stripe_customer on public.user_stripe (stripe_customer_id);
create index if not exists idx_user_stripe_customer_subscription on public.user_stripe (stripe_customer_id, stripe_subscription_id);
create unique index if not exists uq_user_stripe_subscription_id on public.user_stripe (stripe_subscription_id) where stripe_subscription_id is not null;
-- Also ensure uniqueness by customer_id to allow upsert fallback when subscription_id is not yet set
create unique index if not exists uq_user_stripe_customer_id on public.user_stripe (stripe_customer_id) where stripe_customer_id is not null;

-- 追加配信先メールアドレスの保存テーブル（user_stripe と 1:N）
create table if not exists public.recipient_emails (
  id bigserial primary key,
  user_stripe_id bigint references public.user_stripe(id) on delete cascade,
  plan text,                      -- 'lite' | 'business' | null（保存時点のプラン）
  email text not null,
  created_via text,               -- 'initial' | 'addon' | null
  pending_removal boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_recipient_emails_user_stripe on public.recipient_emails (user_stripe_id);
create index if not exists idx_recipient_emails_email on public.recipient_emails (email);

-- メールアドレスは全体でユニーク
do $$ begin
  alter table public.recipient_emails
    add constraint recipient_unique_email unique (email);
exception when duplicate_object then null; end $$;
