name = "lp-mypage"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]  # Node.js API互換を有効化

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
